<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-04-05T10:09:53Z" name="Default suite" finished-at="2019-04-05T10:09:53Z" duration-ms="36">
    <groups>
    </groups>
    <test started-at="2019-04-05T10:09:53Z" name="Default test" finished-at="2019-04-05T10:09:53Z" duration-ms="36">
      <class name="testClasses.TestNG_DependentTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="setUp" finished-at="2019-04-05T10:09:53Z" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testMethod2()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="testMethod2" finished-at="2019-04-05T10:09:53Z" duration-ms="6" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [3]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at testClasses.TestNG_DependentTests.testMethod2(TestNG_DependentTests.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod2 -->
        <test-method signature="testMethod4()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="testMethod4" finished-at="2019-04-05T10:09:53Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod4 -->
        <test-method signature="testMethod1()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="testMethod1" finished-at="2019-04-05T10:09:53Z" depends-on-methods="testClasses.TestNG_DependentTests.testMethod2" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod1 -->
        <test-method signature="testMethod3()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="testMethod3" finished-at="2019-04-05T10:09:53Z" depends-on-methods="testClasses.TestNG_DependentTests.testMethod1" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMethod3 -->
        <test-method is-config="true" signature="clearUp()[pri:0, instance:testClasses.TestNG_DependentTests@45c7e403]" started-at="2019-04-05T10:09:53Z" name="clearUp" finished-at="2019-04-05T10:09:53Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearUp -->
      </class> <!-- testClasses.TestNG_DependentTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
